package vps

import (
	"bytes"
	"encoding/json"
	"fmt"
	"path"

	"github.com/j75689/anyship/spec"
)

// composeFile mirrors the subset of the Compose specification anyship renders.
// It is written as JSON, which is valid YAML, so no YAML encoder is needed and
// output is deterministic (encoding/json sorts map keys).
type composeFile struct {
	Name     string                    `json:"name"`
	Services map[string]composeService `json:"services"`
	Volumes  map[string]struct{}       `json:"volumes,omitempty"`
	Secrets  map[string]composeSecret  `json:"secrets,omitempty"`
}

type composeService struct {
	Image       string            `json:"image,omitempty"`
	Build       *composeBuild     `json:"build,omitempty"`
	Entrypoint  []string          `json:"entrypoint,omitempty"`
	Command     []string          `json:"command,omitempty"`
	Ports       []string          `json:"ports,omitempty"`
	Volumes     []string          `json:"volumes,omitempty"`
	Environment map[string]string `json:"environment,omitempty"`
	Secrets     []string          `json:"secrets,omitempty"`
	DependsOn   []string          `json:"depends_on,omitempty"`
	Healthcheck *composeHealth    `json:"healthcheck,omitempty"`
	Deploy      *composeDeploy    `json:"deploy,omitempty"`
	Restart     string            `json:"restart"`
}

type composeBuild struct {
	Context    string `json:"context"`
	Dockerfile string `json:"dockerfile,omitempty"`
}

type composeHealth struct {
	Test []string `json:"test"`
}

type composeDeploy struct {
	Replicas int `json:"replicas"`
}

type composeSecret struct {
	File string `json:"file"`
}

// contextDir is where a service's build context lands on the host, relative
// to the deployment directory.
func contextDir(service string) string {
	return path.Join("src", service)
}

// composeService renders one spec service. argv is the already-split start
// command, or nil to keep the image's own entrypoint and command.
func renderService(name string, svc *spec.Service, argv []string) composeService {
	out := composeService{
		Image:       svc.Image,
		Environment: svc.Env,
		Secrets:     svc.Secrets,
		DependsOn:   svc.DependsOn,
		Restart:     "unless-stopped",
	}
	if len(out.Environment) == 0 {
		out.Environment = nil
	}
	if svc.Dockerfile != "" {
		out.Build = &composeBuild{Context: contextDir(name), Dockerfile: svc.Dockerfile}
	}
	if len(argv) > 0 {
		// Overriding the entrypoint also clears the image's default command,
		// so the spec's start command runs exactly as written.
		out.Entrypoint = argv[:1]
		out.Command = argv[1:]
	}
	for _, p := range svc.Ports {
		if p.Exposure != spec.ExposurePublic {
			continue // reachable from other services by name on the project network
		}
		if p.Protocol != spec.ProtocolUDP {
			out.Ports = append(out.Ports, fmt.Sprintf("%d:%d", p.Port, p.Port))
		}
		if p.Protocol == spec.ProtocolUDP || p.Protocol == spec.ProtocolTCPUDP {
			out.Ports = append(out.Ports, fmt.Sprintf("%d:%d/udp", p.Port, p.Port))
		}
	}
	for _, v := range svc.Volumes {
		out.Volumes = append(out.Volumes, v.Name+":"+v.MountPath)
	}
	if svc.HealthCheck != nil && svc.HealthCheck.Command != "" {
		out.Healthcheck = &composeHealth{Test: []string{"CMD-SHELL", svc.HealthCheck.Command}}
	}
	if svc.Replicas > 1 {
		out.Deploy = &composeDeploy{Replicas: svc.Replicas}
	}
	return out
}

func renderCompose(c composeFile) ([]byte, error) {
	var buf bytes.Buffer
	buf.WriteString("# Generated by anyship from anyship.json. Edit anyship.json instead; this file is overwritten.\n")
	enc := json.NewEncoder(&buf)
	enc.SetEscapeHTML(false)
	enc.SetIndent("", "  ")
	if err := enc.Encode(c); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}
