package dockerfile

import (
	"errors"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/j75689/anyship/internal/spectest"
	"github.com/j75689/anyship/spec"
)

func context(t *testing.T, files map[string]string) string {
	t.Helper()
	dir := t.TempDir()
	for name, contents := range files {
		if err := os.WriteFile(filepath.Join(dir, name), []byte(contents), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	return dir
}

func service(t *testing.T, src string) *spec.Service {
	t.Helper()
	s, err := spectest.Parse(`{"name": "app", "services": {"web": ` + src + `}}`)
	if err != nil {
		t.Fatal(err)
	}
	return s.Services["web"]
}

func generate(t *testing.T, svc string, files map[string]string) string {
	t.Helper()
	r, err := Generate(service(t, svc), context(t, files))
	if err != nil {
		t.Fatal(err)
	}
	return string(r.Dockerfile)
}

func wantLines(t *testing.T, dockerfile string, lines ...string) {
	t.Helper()
	for _, line := range lines {
		if !strings.Contains(dockerfile, line+"\n") {
			t.Errorf("Dockerfile is missing line %q:\n%s", line, dockerfile)
		}
	}
}

func refuseLines(t *testing.T, dockerfile string, lines ...string) {
	t.Helper()
	for _, line := range lines {
		if strings.Contains(dockerfile, line) {
			t.Errorf("Dockerfile should not contain %q:\n%s", line, dockerfile)
		}
	}
}

func TestNode(t *testing.T) {
	got := generate(t,
		`{"kind": "server", "start": "npm run start", "build": {"command": "npm run build"}, "ports": [{"port": 3000}], "runtime": {"language": "javascript"}}`,
		map[string]string{"package.json": "{}", "package-lock.json": "{}"})
	wantLines(t, got,
		"FROM node:lts-slim",
		"WORKDIR /app",
		"COPY . .",
		"RUN npm ci",
		"RUN npm run build",
		"ENV NODE_ENV=production",
		"ENV PORT=3000",
		"EXPOSE 3000",
		`CMD ["npm","run","start"]`,
	)
	if !strings.HasPrefix(got, "# Generated by anyship.") {
		t.Errorf("missing header:\n%s", got)
	}
}

func TestNodePackageManagers(t *testing.T) {
	svc := `{"kind": "server", "start": "pnpm run start"}`
	pnpm := generate(t, svc, map[string]string{"package.json": `{"packageManager": "pnpm@9.12.0+sha512.abc"}`, "pnpm-lock.yaml": ""})
	wantLines(t, pnpm, "RUN npm install -g pnpm@9.12.0", "RUN pnpm install --frozen-lockfile")

	bun := generate(t, svc, map[string]string{"package.json": "{}", "bun.lock": ""})
	wantLines(t, bun, "FROM oven/bun:1-slim", "RUN bun install --frozen-lockfile")

	berry := generate(t, svc, map[string]string{"package.json": "{}", "yarn.lock": "", ".yarnrc.yml": ""})
	wantLines(t, berry, "RUN npm install -g corepack && corepack enable", "RUN yarn install --immutable")

	classic := generate(t, svc, map[string]string{"package.json": "{}", "yarn.lock": ""})
	wantLines(t, classic, "RUN yarn install --frozen-lockfile")
	refuseLines(t, classic, "corepack")

	noLock := generate(t, svc, map[string]string{"package.json": "{}"})
	wantLines(t, noLock, "RUN npm install")
}

func TestPython(t *testing.T) {
	reqs := generate(t, `{"kind": "server", "start": "gunicorn app:app --bind 0.0.0.0:8000", "ports": [{"port": 8000}]}`,
		map[string]string{"requirements.txt": "flask\ngunicorn\n"})
	wantLines(t, reqs,
		"FROM python:3-slim",
		"RUN pip install --no-cache-dir -r requirements.txt",
		"ENV PORT=8000",
		`CMD ["gunicorn","app:app","--bind","0.0.0.0:8000"]`,
	)

	pyproject := generate(t, `{"kind": "server", "start": "python main.py", "runtime": {"language": "python"}}`,
		map[string]string{"pyproject.toml": "[project]\nname = \"x\"\n"})
	wantLines(t, pyproject, "RUN pip install --no-cache-dir .")
}

func TestGoCopiesOnlyTheBinary(t *testing.T) {
	got := generate(t, `{"kind": "server", "build": {"command": "go build -o bin/api ./cmd/api"}, "start": "./bin/api --verbose", "ports": [{"port": 8080}], "runtime": {"language": "go"}}`,
		map[string]string{"go.mod": "module x\n"})
	wantLines(t, got,
		"FROM golang:1 AS build",
		"ENV CGO_ENABLED=0",
		"RUN go build -o bin/api ./cmd/api",
		"FROM debian:stable-slim",
		"COPY --from=build /src/bin/api ./bin/api",
		"EXPOSE 8080",
		`CMD ["./bin/api","--verbose"]`,
	)
}

func TestGoRunInBuildImageWhenStartIsNotABuildOutput(t *testing.T) {
	got := generate(t, `{"kind": "server", "build": {"command": "go mod download"}, "start": "go run .", "runtime": {"language": "go"}}`, nil)
	wantLines(t, got, "FROM golang:1 AS build", `CMD ["go","run","."]`)
	refuseLines(t, got, "debian", "COPY --from")
}

func TestRust(t *testing.T) {
	got := generate(t, `{"kind": "server", "build": {"command": "cargo build --release"}, "start": "./target/release/proxy", "runtime": {"language": "rust"}}`,
		map[string]string{"Cargo.toml": ""})
	wantLines(t, got,
		"FROM rust:1 AS build",
		"RUN cargo build --release",
		"FROM debian:stable-slim",
		"COPY --from=build /src/target/release/proxy ./target/release/proxy",
		`CMD ["./target/release/proxy"]`,
	)
}

func TestStatic(t *testing.T) {
	plain := generate(t, `{"kind": "static", "build": {"output": "public"}}`, map[string]string{"index.html": ""})
	wantLines(t, plain, "FROM nginx:alpine", "COPY public/ /usr/share/nginx/html/", "EXPOSE 80")
	refuseLines(t, plain, "node")

	built := generate(t, `{"kind": "static", "build": {"command": "npm run build", "output": "dist"}}`,
		map[string]string{"package.json": "{}", "package-lock.json": ""})
	wantLines(t, built,
		"FROM node:lts-slim AS build",
		"RUN npm ci",
		"RUN npm run build",
		"FROM nginx:alpine",
		"COPY --from=build /app/dist/ /usr/share/nginx/html/",
	)
}

// TestStaticOutputIsASlashPathEverywhere covers a build.output written with
// Windows separators. The COPY line runs inside a Linux image, so the generated
// Dockerfile must come out the same whatever the deployer runs. filepath.ToSlash
// used to do this job, and it does nothing at all on Linux.
func TestStaticOutputIsASlashPathEverywhere(t *testing.T) {
	// Through a spec, which normalizes separators for every adapter.
	wantLines(t, generate(t, `{"kind": "static", "build": {"output": "dist\\assets"}}`, nil),
		"COPY dist/assets/ /usr/share/nginx/html/")

	// And through Generate on its own, which any caller may reach.
	r, err := Generate(&spec.Service{Kind: spec.KindStatic, Build: &spec.Build{Output: `dist\assets`}}, t.TempDir())
	if err != nil {
		t.Fatal(err)
	}
	wantLines(t, string(r.Dockerfile), "COPY dist/assets/ /usr/share/nginx/html/")
	refuseLines(t, string(r.Dockerfile), `\`)
}

func TestPortsAndShellFallback(t *testing.T) {
	got := generate(t,
		`{"kind": "server", "start": "node a.js | tee log", "ports": [{"port": 9000, "protocol": "udp"}, {"port": 30303, "protocol": "tcp+udp"}], "runtime": {"language": "javascript"}}`,
		map[string]string{"package.json": "{}"})
	wantLines(t, got,
		"ENV PORT=30303",
		"EXPOSE 9000/udp",
		"EXPOSE 30303/tcp 30303/udp",
		`CMD ["sh","-c","node a.js | tee log"]`,
	)
}

func TestIgnoreFileKeepsProjectRules(t *testing.T) {
	r, err := Generate(service(t, `{"kind": "static"}`), context(t, map[string]string{".dockerignore": "secrets/\n*.pem"}))
	if err != nil {
		t.Fatal(err)
	}
	ignore := string(r.Ignore)
	for _, want := range []string{"secrets/\n*.pem\n", ".git\n", Filename + "\n", IgnoreFilename + "\n"} {
		if !strings.Contains(ignore, want) {
			t.Errorf("ignore file missing %q:\n%s", want, ignore)
		}
	}
}

func TestUnsupported(t *testing.T) {
	for svc, reason := range map[string]string{
		`{"kind": "server", "start": "java -jar app.jar", "runtime": {"language": "java"}}`: "java isn't supported",
		`{"kind": "server", "start": "./app"}`:                                              "couldn't tell which language",
		`{"kind": "worker", "image": "x"}`:                                                  "no start command",
		`{"kind": "server", "start": "./bin/x", "runtime": {"language": "go"}}`:             "no build.command",
		`{"kind": "static", "build": {"command": "make site"}}`:                             "only supported for JavaScript",
		`{"kind": "static", "build": {"output": "../outside"}}`:                             "must stay inside",
		// A Windows drive is outside the service directory too, and path.IsAbs
		// sees neither of these as absolute.
		`{"kind": "static", "build": {"output": "C:\\dist"}}`:                                               "must stay inside",
		`{"kind": "static", "build": {"output": "d:dist"}}`:                                                 "must stay inside",
		`{"kind": "server", "start": "x", "build": {"command": "a\nb"}, "runtime": {"language": "python"}}`: "single line",
	} {
		_, err := Generate(service(t, svc), t.TempDir())
		var u *UnsupportedError
		if !errors.As(err, &u) || !strings.Contains(u.Reason, reason) {
			t.Errorf("Generate(%s) error = %v, want an UnsupportedError mentioning %q", svc, err, reason)
		}
	}
}
