// Package dockerfile generates a Dockerfile for a service that doesn't have
// one, from the language, build and start commands in its spec.
//
// Output is deterministic and deliberately plain, so users can read it, copy
// it into their repo and take over from there.
package dockerfile

import (
	"bytes"
	"encoding/json"
	"fmt"
	"os"
	"path"
	"path/filepath"
	"strings"

	"github.com/j75689/anyship/internal/shellwords"
	"github.com/j75689/anyship/spec"
)

const (
	// Filename is the generated Dockerfile's name inside the build context.
	Filename = "Dockerfile.anyship"
	// IgnoreFilename is the per-Dockerfile ignore file BuildKit reads for Filename.
	// It takes precedence over .dockerignore, so it includes that file's rules.
	IgnoreFilename = Filename + ".dockerignore"
	// StaticPort is the port generated static-site images serve on.
	StaticPort = 80
)

const header = "# Generated by anyship. To customize the build, commit your own Dockerfile\n# and set services.<name>.dockerfile in anyship.json.\n"

// Result holds the generated files, to be placed at the root of the build context.
type Result struct {
	Dockerfile []byte
	Ignore     []byte
}

// UnsupportedError explains why no Dockerfile could be generated.
type UnsupportedError struct{ Reason string }

func (e *UnsupportedError) Error() string { return e.Reason }

func unsupported(format string, args ...any) error {
	return &UnsupportedError{Reason: fmt.Sprintf(format, args...)}
}

// Generate writes a Dockerfile for svc. contextDir is the service's source
// directory; it is read (lockfiles, manifests) but never modified.
func Generate(svc *spec.Service, contextDir string) (*Result, error) {
	ctx := buildContext{dir: contextDir}
	w := &writer{}
	w.raw(header)

	var err error
	if svc.Build != nil && strings.Contains(svc.Build.Command, "\n") {
		return nil, unsupported("build.command must be a single line")
	}
	if svc.Kind == spec.KindStatic {
		err = static(w, svc, ctx)
	} else {
		if strings.TrimSpace(svc.Start) == "" {
			return nil, unsupported("the service has no start command")
		}
		switch lang := language(svc, ctx); lang {
		case "javascript", "typescript":
			err = node(w, svc, ctx)
		case "python":
			python(w, svc, ctx)
		case "go":
			err = compiled(w, svc, "golang:1", "ENV CGO_ENABLED=0")
		case "rust":
			err = compiled(w, svc, "rust:1", "")
		case "":
			err = unsupported("couldn't tell which language the service uses; set services.<name>.runtime.language")
		default:
			err = unsupported("generating Dockerfiles for %s isn't supported yet", lang)
		}
	}
	if err != nil {
		return nil, err
	}
	return &Result{Dockerfile: w.bytes(), Ignore: ctx.ignoreFile()}, nil
}

func node(w *writer, svc *spec.Service, ctx buildContext) error {
	nodeBase(w, ctx, "")
	if svc.Build != nil && svc.Build.Command != "" {
		w.line("RUN " + svc.Build.Command)
	}
	w.line("ENV NODE_ENV=production")
	expose(w, svc.Ports)
	w.line(cmd(svc.Start))
	return nil
}

// nodeBase starts a Node.js stage that has the project's dependencies installed.
func nodeBase(w *writer, ctx buildContext, stage string) {
	pm := ctx.packageManager()
	base := "node:lts-slim"
	if pm == "bun" {
		base = "oven/bun:1-slim"
	}
	if stage != "" {
		base += " AS " + stage
	}
	w.line("FROM " + base)
	w.line("WORKDIR /app")
	switch {
	case pm == "pnpm":
		w.line("RUN npm install -g " + ctx.pinnedPackageManager("pnpm"))
	case pm == "yarn" && ctx.has(".yarnrc.yml"):
		// Yarn 2+ is provisioned by corepack, which newer Node images no longer bundle.
		w.line("RUN npm install -g corepack && corepack enable")
	}
	w.line("COPY . .")
	w.line("RUN " + ctx.installCommand(pm))
}

func python(w *writer, svc *spec.Service, ctx buildContext) {
	w.line("FROM python:3-slim")
	w.line("ENV PYTHONDONTWRITEBYTECODE=1 PYTHONUNBUFFERED=1")
	w.line("WORKDIR /app")
	w.line("COPY . .")
	switch {
	case ctx.has("requirements.txt"):
		w.line("RUN pip install --no-cache-dir -r requirements.txt")
	case ctx.has("pyproject.toml"):
		w.line("RUN pip install --no-cache-dir .")
	}
	if svc.Build != nil && svc.Build.Command != "" {
		w.line("RUN " + svc.Build.Command)
	}
	expose(w, svc.Ports)
	w.line(cmd(svc.Start))
}

// compiled builds in a toolchain image. When start runs a file the build
// produced (like ./bin/server), only that file is copied into a slim runtime
// image; otherwise the service runs in the build image.
func compiled(w *writer, svc *spec.Service, builder, buildEnv string) error {
	if svc.Build == nil || svc.Build.Command == "" {
		return unsupported("the service has no build.command")
	}
	w.line("FROM " + builder + " AS build")
	w.line("WORKDIR /src")
	if buildEnv != "" {
		w.line(buildEnv)
	}
	w.line("COPY . .")
	w.line("RUN " + svc.Build.Command)

	if artifact, ok := localExecutable(svc.Start); ok {
		w.line("")
		w.line("FROM debian:stable-slim")
		w.line("RUN apt-get update && apt-get install -y --no-install-recommends ca-certificates && rm -rf /var/lib/apt/lists/*")
		w.line("WORKDIR /app")
		w.line(fmt.Sprintf("COPY --from=build /src/%s ./%s", artifact, artifact))
	}
	expose(w, svc.Ports)
	w.line(cmd(svc.Start))
	return nil
}

func static(w *writer, svc *spec.Service, ctx buildContext) error {
	output := "."
	if svc.Build != nil && svc.Build.Output != "" {
		output = path.Clean(filepath.ToSlash(svc.Build.Output))
	}
	if path.IsAbs(output) || output == ".." || strings.HasPrefix(output, "../") {
		return unsupported("build.output %q must stay inside the service directory", output)
	}

	if svc.Build != nil && svc.Build.Command != "" {
		if !ctx.has("package.json") {
			return unsupported("static build commands are only supported for JavaScript projects; add a Dockerfile instead")
		}
		nodeBase(w, ctx, "build")
		w.line("RUN " + svc.Build.Command)
		w.line("")
		w.line("FROM nginx:alpine")
		w.line(fmt.Sprintf("COPY --from=build /app/%s/ /usr/share/nginx/html/", output))
	} else {
		w.line("FROM nginx:alpine")
		w.line(fmt.Sprintf("COPY %s/ /usr/share/nginx/html/", output))
	}
	w.line(fmt.Sprintf("EXPOSE %d", StaticPort))
	return nil
}

// expose declares the service's ports and passes the first TCP one as $PORT,
// which most frameworks read.
func expose(w *writer, ports []spec.Port) {
	envSet := false
	for _, p := range ports {
		if p.Protocol != spec.ProtocolUDP && !envSet {
			w.line(fmt.Sprintf("ENV PORT=%d", p.Port))
			envSet = true
		}
	}
	for _, p := range ports {
		switch p.Protocol {
		case spec.ProtocolUDP:
			w.line(fmt.Sprintf("EXPOSE %d/udp", p.Port))
		case spec.ProtocolTCPUDP:
			w.line(fmt.Sprintf("EXPOSE %d/tcp %d/udp", p.Port, p.Port))
		default:
			w.line(fmt.Sprintf("EXPOSE %d", p.Port))
		}
	}
}

// cmd renders start in exec form so the process receives signals directly,
// falling back to sh -c only when start needs a shell.
func cmd(start string) string {
	argv, err := shellwords.Split(start)
	if err != nil {
		argv = []string{"sh", "-c", start}
	}
	var buf bytes.Buffer
	enc := json.NewEncoder(&buf)
	enc.SetEscapeHTML(false)
	_ = enc.Encode(argv) // a []string always encodes
	return "CMD " + strings.TrimSpace(buf.String())
}

// localExecutable returns the path of start's program when it is a file
// inside the build context, like ./bin/server.
func localExecutable(start string) (string, bool) {
	argv, err := shellwords.Split(start)
	if err != nil || !strings.HasPrefix(argv[0], "./") {
		return "", false
	}
	clean := path.Clean(argv[0])
	if clean == "." || strings.HasPrefix(clean, "../") {
		return "", false
	}
	return clean, true
}

func language(svc *spec.Service, ctx buildContext) string {
	if svc.Runtime != nil && svc.Runtime.Language != "" {
		return svc.Runtime.Language
	}
	for _, m := range []struct{ file, lang string }{
		{"package.json", "javascript"},
		{"go.mod", "go"},
		{"Cargo.toml", "rust"},
		{"requirements.txt", "python"},
		{"pyproject.toml", "python"},
	} {
		if ctx.has(m.file) {
			return m.lang
		}
	}
	return ""
}

type writer struct{ b strings.Builder }

func (w *writer) raw(s string)  { w.b.WriteString(s) }
func (w *writer) line(s string) { w.b.WriteString(s + "\n") }
func (w *writer) bytes() []byte { return []byte(w.b.String()) }

// buildContext reads the service's source directory.
type buildContext struct{ dir string }

func (c buildContext) has(name string) bool {
	_, err := os.Stat(filepath.Join(c.dir, name))
	return err == nil
}

func (c buildContext) read(name string) string {
	data, err := os.ReadFile(filepath.Join(c.dir, name))
	if err != nil {
		return ""
	}
	return string(data)
}

// packageManager picks the JavaScript package manager from lockfiles, then
// the packageManager field of package.json, defaulting to npm.
func (c buildContext) packageManager() string {
	for _, l := range []struct{ file, pm string }{
		{"bun.lock", "bun"}, {"bun.lockb", "bun"}, {"pnpm-lock.yaml", "pnpm"}, {"yarn.lock", "yarn"}, {"package-lock.json", "npm"},
	} {
		if c.has(l.file) {
			return l.pm
		}
	}
	if name, _, _ := strings.Cut(c.packageManagerField(), "@"); name != "" {
		return name
	}
	return "npm"
}

func (c buildContext) packageManagerField() string {
	var pkg struct {
		PackageManager string `json:"packageManager"`
	}
	_ = json.Unmarshal([]byte(c.read("package.json")), &pkg)
	return pkg.PackageManager
}

// pinnedPackageManager returns e.g. "pnpm@9.12.0" when package.json pins
// that version, otherwise just the name.
func (c buildContext) pinnedPackageManager(name string) string {
	field := c.packageManagerField()
	if strings.HasPrefix(field, name+"@") {
		version, _, _ := strings.Cut(strings.TrimPrefix(field, name+"@"), "+")
		if version != "" {
			return name + "@" + version
		}
	}
	return name
}

func (c buildContext) installCommand(pm string) string {
	switch pm {
	case "pnpm":
		if c.has("pnpm-lock.yaml") {
			return "pnpm install --frozen-lockfile"
		}
		return "pnpm install"
	case "yarn":
		switch {
		case !c.has("yarn.lock"):
			return "yarn install"
		case c.has(".yarnrc.yml"):
			return "yarn install --immutable"
		default:
			return "yarn install --frozen-lockfile"
		}
	case "bun":
		if c.has("bun.lock") || c.has("bun.lockb") {
			return "bun install --frozen-lockfile"
		}
		return "bun install"
	default:
		if c.has("package-lock.json") {
			return "npm ci"
		}
		return "npm install"
	}
}

// ignoreFile keeps the project's own .dockerignore rules (BuildKit reads the
// per-Dockerfile file instead of .dockerignore) and adds the usual noise.
func (c buildContext) ignoreFile() []byte {
	var b strings.Builder
	if own := c.read(".dockerignore"); own != "" {
		b.WriteString(own)
		if !strings.HasSuffix(own, "\n") {
			b.WriteString("\n")
		}
	}
	b.WriteString("# added by anyship\n.git\n.anyship\nnode_modules\ntarget\n.venv\n__pycache__\n" + Filename + "\n" + IgnoreFilename + "\n")
	return []byte(b.String())
}
