# yaml-language-server: $schema=../../schema/anyship.schema.json
apiVersion: anyship/v1alpha1
kind: App
metadata:
  name: hono-worker
spec:
  services:
    web:
      kind: server
      entry: src/index.ts
      env:
        GREETING: hello
      runtime:
        language: javascript
        framework: hono
        edgeCompatible: true
